# Generated by Django 2.2 on 2020-12-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeHack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='comm_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='HomeHack_app.User'),
        ),
    ]
