# Generated by Django 2.2 on 2020-12-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeHack_app', '0002_auto_20201212_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poster',
            new_name='comment_poster',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='comm_poster',
        ),
    ]
